/* Write a recipe site like Cookpad. */
var recipe = document.createElement('div');
recipe.innerHTML = '<h1>Recipe</h1>';
document.body.appendChild(recipe);
var ingredients = document.createElement('div');
ingredients.innerHTML = '<h2>Ingredients</h2>';
recipe.appendChild(ingredients);
var ingredientsList = document.createElement('ul');
ingredients.appendChild(ingredientsList);
var ingredient = document.createElement('li');
ingredientsList.appendChild(ingredient);
ingredient.innerHTML = '<span>1</span> <span>cup</span> <span>flour</span>';
var ingredient = document.createElement('li');
ingredientsList.appendChild(ingredient);
ingredient.innerHTML = '<span>1</span> <span>cup</span> <span>sugar</span>';
var ingredient = document.createElement('li');
ingredientsList.appendChild(ingredient);
ingredient.innerHTML = '<span>1</span> <span>cup</span> <span>butter</span>';
var directions = document.createElement('div');
directions.innerHTML = '<h2>Directions</h2>';
recipe.appendChild(directions);
var directionsList = document.createElement('ol');
directions.appendChild(directionsList);
var direction = document.createElement('li');
directionsList.appendChild(direction);
direction.innerHTML = '<span>Preheat</span> <span>oven</span> <span>to</span> <span>350</span> <span>degrees</span>';
var direction = document.createElement('li');
directionsList.appendChild(direction);
direction.innerHTML = '<span>Mix</span> <span>flour</span> <span>and</span> <span>sugar</span>';
var direction = document.createElement('li');
directionsList.appendChild(direction);
direction.innerHTML = '<span>Stir</span> <span>in</span> <span>butter</span>';
var direction = document.createElement('li');
directionsList.appendChild(direction);
direction.innerHTML = '<span>Press</span> <span>into</span> <span>buttered</span> <span>baking</span> <span>pan</span>';
var direction = document.createElement('li');
directionsList.appendChild(direction);
direction.innerHTML = '<span>Bake</span> <span>for</span> <span>30</span> <span>minutes</span>';
